/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  UserIdentityACL,
  UserIdentityACLInterface,
} from "../../../contracts/userIdentity/UserIdentityACL";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerNotAllowed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "serviceProvider",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approval",
        type: "bool",
      },
    ],
    name: "authorize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isAllowedToExecuteCallFor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "isAllowedToExecuteCallFor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610229806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80630ff51e991461004657806325d4a9be1461009c5780632d1fb389146100af575b600080fd5b610088610054366004610169565b73ffffffffffffffffffffffffffffffffffffffff1660009081526020818152604080832033845290915290205460ff1690565b604051901515815260200160405180910390f35b6100886100aa366004610184565b610102565b6101006100bd3660046101b7565b3360009081526020818152604080832073ffffffffffffffffffffffffffffffffffffffff95909516835293905291909120805460ff1916911515919091179055565b005b73ffffffffffffffffffffffffffffffffffffffff80831660009081526020818152604080832093851683529290529081205460ff165b9392505050565b803573ffffffffffffffffffffffffffffffffffffffff8116811461016457600080fd5b919050565b60006020828403121561017b57600080fd5b61013982610140565b6000806040838503121561019757600080fd5b6101a083610140565b91506101ae60208401610140565b90509250929050565b600080604083850312156101ca57600080fd5b6101d383610140565b9150602083013580151581146101e857600080fd5b80915050925092905056fea26469706673582212200e4bcbf989fa9dc1a3085fa8d1d40e77b55652f69f8f46c5187d370ee5bda9fa64736f6c63430008100033";

type UserIdentityACLConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UserIdentityACLConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UserIdentityACL__factory extends ContractFactory {
  constructor(...args: UserIdentityACLConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<UserIdentityACL> {
    return super.deploy(overrides || {}) as Promise<UserIdentityACL>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): UserIdentityACL {
    return super.attach(address) as UserIdentityACL;
  }
  override connect(signer: Signer): UserIdentityACL__factory {
    return super.connect(signer) as UserIdentityACL__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UserIdentityACLInterface {
    return new utils.Interface(_abi) as UserIdentityACLInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UserIdentityACL {
    return new Contract(address, _abi, signerOrProvider) as UserIdentityACL;
  }
}
