/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TropykusBorrowingService__factory } from "./TropykusBorrowingService__factory";
export { TropykusLendingService__factory } from "./TropykusLendingService__factory";
