/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  $RIFGateway,
  $RIFGatewayInterface,
} from "../../../contracts-exposed/RIFGateway.sol/$RIFGateway";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "$_bar",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "foo",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101e8806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063209d40041461003b578063c298557814610059575b600080fd5b610043610077565b6040516100509190610190565b60405180910390f35b610061610086565b60405161006e9190610190565b60405180910390f35b60606100816100c3565b905090565b60606040518060400160405280600381526020017f6261720000000000000000000000000000000000000000000000000000000000815250905090565b60606040518060400160405280600381526020017f62617a0000000000000000000000000000000000000000000000000000000000815250905090565b600081519050919050565b600082825260208201905092915050565b60005b8381101561013a57808201518184015260208101905061011f565b60008484015250505050565b6000601f19601f8301169050919050565b600061016282610100565b61016c818561010b565b935061017c81856020860161011c565b61018581610146565b840191505092915050565b600060208201905081810360008301526101aa8184610157565b90509291505056fea2646970667358221220ff8b6bc59a782a1c4108077b2ff3b71d3072e1b35ae995e10e91b8968ab2b99a64736f6c63430008100033";

type $RIFGatewayConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: $RIFGatewayConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class $RIFGateway__factory extends ContractFactory {
  constructor(...args: $RIFGatewayConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<$RIFGateway> {
    return super.deploy(overrides || {}) as Promise<$RIFGateway>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): $RIFGateway {
    return super.attach(address) as $RIFGateway;
  }
  override connect(signer: Signer): $RIFGateway__factory {
    return super.connect(signer) as $RIFGateway__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): $RIFGatewayInterface {
    return new utils.Interface(_abi) as $RIFGatewayInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): $RIFGateway {
    return new Contract(address, _abi, signerOrProvider) as $RIFGateway;
  }
}
