/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  $IServiceData,
  $IServiceDataInterface,
} from "../../../../contracts-exposed/services/IServiceData.sol/$IServiceData";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212202f8e9f130b65f379ba5743a712c35e44b350691c63ba261bfd9e730944069d0e64736f6c63430008100033";

type $IServiceDataConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: $IServiceDataConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class $IServiceData__factory extends ContractFactory {
  constructor(...args: $IServiceDataConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<$IServiceData> {
    return super.deploy(overrides || {}) as Promise<$IServiceData>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): $IServiceData {
    return super.attach(address) as $IServiceData;
  }
  override connect(signer: Signer): $IServiceData__factory {
    return super.connect(signer) as $IServiceData__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): $IServiceDataInterface {
    return new utils.Interface(_abi) as $IServiceDataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): $IServiceData {
    return new Contract(address, _abi, signerOrProvider) as $IServiceData;
  }
}
